### ISSUE TITLE
unable to generate task for perevents plugin

### ISSUE THREAD

**Issue by imvisiontech** [intelsdi-x/snap-plugin-collector-perfevents#24]
Hi, 
I'm currently trying to run perfevent task and I get a several failures: "connection is shut down" (I think it follows an EOF expection) and in turn the error changes to "could not select a plugin". the collected metrics are taken from the snapctl metric list for the perfevent plugin. I am using snapd version 1.3. Is it a known issue?
I am running on ubuntu release 14.04
and it seems that the path for the metadata that I found through perf stats is different then that suggested for perevenets using the ./snapctl metrics list

**Comment by nanliu** [comment]
@imvisiontech, please review https://github.com/intelsdi-x/snap/pull/1456, and see if the daemon control setting `max_plugin_restarts` to a high value resolve this. If you are able to try the latest build, you can set `max_plugin_restarts: -1` to disable this behavior. We also provided additional logging message to indicate the plugin has been disabled due to multiple failures:

```
level=warning msg="plugin disabled due to exceeding restart limit: 10"
```

A linux test build of the latest version of snap is available at:
https://s3-us-west-2.amazonaws.com/snap.ci.snap-telemetry.io/snap/latest/linux/x86_64/snapteld

**Comment by nanliu** [comment]
Based on other user's feedback and our test results, we believe this is fixed per comment above. If you still run into this issue, please feel free to reopen this issue.
